 #include <stdio.h>
 int main()
 {
    int i,x[5];
    for(i=0;i<5;i++)
     scanf("%d",&x[i]);
    
    return 0; 
 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               