#Python字符串判断
print("测试实例1")
str="runoob.com"
print(str.isalnum())#判断所有字符都是数字或者字母
print(str.isalpha())#判断所有字符都是字母
print(str.isdigit())#判断所有字符都是数字
print(str.islower())#判断所有字符都是小写
print(str.isupper())#判断所有字符都是大写
print(str.istitle())#判断所有单词都是首字母大写
print(str.isspace())
print(str.upper())
print(str.lower())
print(str.capitalize())
print(str.title())
